[package]
name = "bevy_proto_pixel_palette"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.9.0", features = ["dynamic"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
